### ISSUE TITLE
Installing the new version of Flash Player only gave Waterfox the Flash Player EOL notice

### ISSUE THREAD

**Issue by dum-du-m** [CleanFlash/installer#17] opened 2021-08-01 13:20 UTC
Title.
![image](https://user-images.githubusercontent.com/79086250/127772428-96120a5f-8f7d-40e5-857b-4caff83fac5b.png)

**Comment by DraconicNEO** [comment] 2021-08-02 20:42
I'm now going back to my previous statement saying that you shouldn't use a version after 18.0.0.160 well before Adobe Was thinking of kicking people off Flash.

**Comment by DraconicNEO** [comment] 2021-08-02 20:57
This is probably also an issue with [Flashpatch](https://github.com/darktohka/FlashPatch) since the Installer uses versions of Flash that have been Patched with Flashpatch. Might need to look into that as well @darktohka.

**Comment by DraconicNEO** [comment] 2021-08-22 23:21
@darktohka Has this issue been fixed on the Newer CleanFlash/Flashpatch versions?

**Comment by darktohka** [comment] 2021-08-22 23:24
This issue is out of scope for the project. There is nothing wrong with the patch itself. This is expected behaviour that happens when Flash tries to load a SWF that is not allowed by the URL allowlist loaded from the current mms.cfg configuration. Most likely dum-du-m has installed the patched version after installing Newgrounds Player, which adds an allowlist setting that only allows Newgrounds SWFs to be played.

**Comment by DraconicNEO** [comment] 2021-08-23 01:42
> 
> 
> This issue is out of scope for the project. There is nothing wrong with the patch itself. This is expected behaviour that happens when Flash tries to load a SWF that is not allowed by the URL allowlist loaded from the current mms.cfg configuration. Most likely dum-du-m has installed the patched version after installing Newgrounds Player, which adds an allowlist setting that only allows Newgrounds SWFs to be played.

Ah I see, was worried there was another killswitch unaccounted for. Glad that's not the case.

**Closed** 2021-10-03 09:35 UTC
